# Generated by Django 4.1.7 on 2023-03-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_credit_id', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('number_phone', models.CharField(max_length=15)),
                ('card_number', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('loan_id', models.IntegerField(null=True)),
                ('user_id_create', models.IntegerField(null=True)),
                ('username_create', models.CharField(max_length=50)),
                ('create_on', models.DateField(null=True)),
                ('modify_date', models.DateField(null=True)),
                ('created_at', models.DateField(null=True)),
                ('modified_at', models.DateField(null=True)),
                ('note', models.TextField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('expiration_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='MatchRule',
            fields=[
                ('match_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_brief_id', models.IntegerField()),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'match_rule',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='MatchRuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('match_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.matchrule')),
            ],
            options={
                'db_table': 'match_rule_detail',
            },
        ),
        migrations.AddField(
            model_name='matchrule',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.rule'),
        ),
    ]
