# Generated by Django 4.1.7 on 2023-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('live', 'live'), ('die', 'die'), ('sold', 'sold')], default='submitted', max_length=30)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('country_name', models.CharField(max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registered_mail',
            },
        ),
        migrations.DeleteModel(
            name='BlacklistFraud',
        ),
        migrations.RemoveField(
            model_name='matchruledetail',
            name='match_rule',
        ),
        migrations.DeleteModel(
            name='MatchRule',
        ),
        migrations.DeleteModel(
            name='MatchRuleDetail',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
